# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    branches:
      ignore: gh-pages

    working_directory: ~/

    steps:
      - run: 
          name: Build and Publish Website
          command: |
            git config --global user.email "se@users.noreply.github.com"
            git config --global user.name "Selçuk Ermaya"
            echo "machine github.com login <GITHUB_USERNAME> password $GITHUB_TOKEN" > ~/.netrc
            pwd
            ls -al
            cd website && yarn install && GIT_USER=se yarn run publish-gh-pages
            echo "Done!"
